spring.application.name=DpiBatchMeetBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/batch_comm_plat
server.port=7390
spring.datasource.username=postgres

spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect